version: '3.7'
services:
  development:
    build: .
    container_name: doppelspeller
    volumes:
        - .:/doppelspeller/
    environment:
        - PROJECT_DATA_PATH=/doppelspeller/data/
        - LLVM_CONFIG=/usr/bin/llvm-config-8
    stdin_open: true
    tty: true
