# Columns
COLUMN_WORDS = 'words'
COLUMN_TITLE_ID = 'title_id'
COLUMN_TITLE = 'title'
COLUMN_TRANSFORMED_TITLE = 'transformed_title'
COLUMN_NUMBER_OF_WORDS = 'number_of_words'
COLUMN_SEQUENCES = 'sequences'
COLUMN_SEQUENCES_MIN_HASH = 'sequences_min_hash'
COLUMN_NUMBER_OF_CHARACTERS = 'number_of_characters'
COLUMN_GENERATED_MISSPELLED_TITLE = 'generated_misspelled_title'
